### ISSUE TITLE
Failed to restore options values

### ISSUE THREAD

**Issue by rm76** [julien-nc/cospend-nc#256]
Hi, after updating to version 1.6.0, when I load the apps/cospend page, all I get is a blank page and this message: Failed to restore options values.
I'm on Nextcloud server latest stable version (28.0.1).

**Comment by julien-nc** [comment]
Php might have cached some files. Try again now. If it still does not work, restart your php-fpm service or your webserver. Any better?

**Comment by jtoloe** [comment]
Restarting php-fpm solved it for me.

**Comment by julien-nc** [comment]
@jtoloe Thanks for the feedback!

**Comment by provokateurin** [comment]
Had the same problem, after reloading twice it was gone.

**Comment by thgoebel** [comment]
Here is an issue that I had after upgrading to 1.6.0 that was fixed by restarting the Docker container Nextcloud runs in.

For me, Cospend was failing with HTTP 500 and throwing the following exceptions:
```
Undefined constant OCA\Cospend\AppInfo\Application::SORT_ORDER_ALPHA in file '/var/www/html/custom_apps/cospend/lib/Service/ProjectService.php' line 1804
Undefined constant OCA\Cospend\AppInfo\Application::SHARE_TYPE_USER in file '/var/www/html/custom_apps/cospend/lib/Service/ProjectService.php' line 1643
```

As said, restarting Nextcloud fixed it. Sorry to hijack this issue, I figured it is not worth to open a new issue for it (since the workaround is trivial), but I wanted to write it down so others who search for the error message can find the fix.
