### ISSUE TITLE
cant add any bill

### ISSUE THREAD

**Issue by albjeremias** [julien-nc/cospend-nc#317]
![image](https://github.com/user-attachments/assets/381ac28d-c926-40c5-8aa6-9621032a2986)

getting the error: "Bill values are not valid"

**Comment by julien-nc** [comment]
This is because there is no member in your project. I wondered how you could even see the bill creation form in this case and realized the "create a bill" button in the central area is displayed even if there is no member.
This button is now only displayed if there is at least on member in the current project.

**Comment by albjeremias** [comment]
I'm really confused, so maybe there should be a warning message saying that?
Also I didn't do any magic, this is how cospend shows up the first time I open in nextcloud.
How come there are no members? I'm not a member? what means to be a member?

thanks
